package net.cydhra.nidhogg.data

import kotlinx.serialization.Serializable

/**
 * A Yggdrasil session. It is (re-)generated by the Yggdrasil service upon calling
 * [authenticate][net.cydhra.nidhogg.YggdrasilClient.authenticate] or
 * [refresh][net.cydhra.nidhogg.YggdrasilClient.refresh]. It contains a secret [accessToken] that is required to
 * authenticate against Mojang games. A client should never store the password, just the access token. It furthermore
 * contains a secret [clientToken] that is chosen by the client and is required to call the refresh function.
 *
 * @param accessToken the session access token
 * @param clientToken the client token used to obtain the session
 */
@Serializable
data class Session(var accessToken: String, var clientToken: String)
